spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      #todo: this is only valid for testing, i need to change it to update once done testing

  datasource:
    url: "jdbc:mysql://localhost:3306/backend"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"